### ISSUE TITLE
Bugs to Look into!

### ISSUE THREAD

**Issue by FerranMarin** [FerranMarin/axie-scholar-utilities#103]
1.  Transfers and morphing seam to be a problem when dealing with LOTS of axies in an account

2. Claims getting stuck! (maybe re-make it async??)

3. For some reason:
""" File "/usr/local/lib/python3.10/site-packages/axie_utils/claims.py", line 194, in execute
    recepit = self.w3.eth.get_transaction_receipt(hash)
"""
Raised and did not catch it!

4. Somewhere in payout we do not use toChecksumAddress for SLP address! (line 102 of scatter)
5. make sure min_ron is a FLOAT!
6. look into csv reader

7. Problem with types in disperseEther!
Provide ronin account that will provide the RON to scatter: ronin:837ea04a3b5d27d59759b8d6c5fe7857fa195fa9
2022-03-30 23:03:22,831 - INFO: I shall scatter ron for my scholars!
2022-03-30 23:03:27,593 - INFO: Account ronin:837ea04a3b5d27d59759b8d6c5fe7857fa195fa9 already has more than the min ron desired
Traceback (most recent call last):
  File "/opt/app/axie_scholar_cli.py", line 492, in <module>
    run_cli()
  File "/opt/app/axie_scholar_cli.py", line 296, in run_cli
    scm.execute()
  File "/opt/app/axie/scatter.py", line 34, in execute
    s.execute()
  File "/usr/local/lib/python3.10/site-packages/axie_utils/scatter.py", line 204, in execute
    return self.execute_ron(gas_price, nonce)
  File "/usr/local/lib/python3.10/site-packages/axie_utils/scatter.py", line 156, in execute_ron
    transaction = self.contract.functions.disperseEther(
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 878, in call
    clone._set_function_info()
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 883, in _set_function_info
    self.abi = find_matching_fn_abi(
  File "/usr/local/lib/python3.10/site-packages/web3/_utils/contracts.py", line 163, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError:
Could not identify the intended function with name disperseEther, positional argument(s) of type (<class 'list'>, <class 'list'>) and keyword argument(s) of type {}.
Found 1 function(s) with the name disperseEther: ['disperseEther(address[],uint256[])']

8. Somehow we passed a list as a bip_path when doing managed_payout!

9. TypeError: Transaction must include these fields: {'nonce'} < what does this means, happens while running payout (I believe that one is already fixed!)

**Comment by FerranMarin** [comment]
Hope that https://github.com/FerranMarin/axie-scholar-utilities/releases/tag/v3.0.3 fixes them.
